version: "3.8"

services:
  # db:
  #   image: postgres
  #   container_name: db
  #   ports:
  #     - "2022:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres

  backend:
    container_name: prof_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://ethics_dashboard:Letmein1!@db:5432/ethics_dashboard # Explicitly setting the DB URL
      - DB_USER=ethics_dashboard
      - DB_PASSWORD=Letmein1!
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ethics_dashboard

    networks:
      - ethicddashboard_shared_network

  frontend:
    container_name: prof_frontend
    build:
      context: ./app/templates
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app/templates:/app
      - /app/node_modules
    depends_on:
      - backend

    networks:
      - ethicddashboard_shared_network

volumes:
  pgdata: {}


networks:
  ethicddashboard_shared_network:
    external: true  # Use Project 1's existing network
